### PR TITLE
fix Android double type

### LINKED ISSUE #20: fix double-type on android
possibly coming from contenteditable, and using the full innerText.

### PR DESCRIPTION
**Pull request by bozdoz**
closes #20

### CODE REVIEW

**Comment by bozdoz** [comment]
Todo: add input event listener: check if any keys are down. If not, wipe the input to disable text suggestion buttons. Maybe even disables swipe

File: src/App.ts [hunk 1]
```diff
@@ -262,14 +251,25 @@ class App {
...
+
+  emptyText = () => {
+    // leaves a character to disable automatic ProperCase in mobile
+    textInput.innerText = '';
+    textInput.innerText = '|';
+  };
+
+  focusText = () => {
+    textInput.focus();
+    window.getSelection()!.collapse(textInput, 1);
```
Comment (bozdoz) [inline src/App.ts:271]: Probably wrap in a try catch

File: src/helpers/getElements.ts [hunk 2]
```diff
@@ -1,5 +1,7 @@
 export const container = document.getElementById('container') as HTMLElement;
-export const textInput = document.getElementById('text-input') as HTMLElement;
+export const textInput = document.getElementById(
+  'text-input'
+) as HTMLInputElement;
```
Comment (bozdoz) [inline src/helpers/getElements.ts:4]: Reverted

**Comment by bozdoz** [comment]
backspace on android fixes it.   Maybe simulate backspace on ENTER or SPACE, or every time

**Comment by bozdoz** [comment]
I think this is as good as it gets
